[theme]
base="light"
primaryColor="rgb(46, 154, 255)"
backgroundColor="#eee"
secondaryBackgroundColor="#ccc"
textColor="#000"
font="sans serif"

[client]
toolbarMode = "minimal"

[global]
developmentMode = false